let adjective, noun, verb, place, adjective2, noun2;
adjective="black";
noun="crow";
noun2="flesh";
place="ruin";
adjective2="red";
verb="angry";
let firstStory;
firstStory="Once upon a time, there was a(n) "+adjective+" "+noun+" who loved to eat "+noun2+". The "+noun+" lived in a "+place+" and had "+adjective2+" nostrils that blew fire when it was "+verb+".";
console.log("First story: "+firstStory);
adjective="slow";
noun="turtle";
noun2="grass";
place="river";
adjective2="black";
verb="angry";
let secondStory;
secondStory="Once upon a time, there was a(n) "+adjective+" "+noun+" who loved to eat "+noun2+". The "+noun+" lived in a "+place+" and had "+adjective2+" nostrils that blew fire when it was "+verb+".";
console.log("Second story: "+secondStory);
